export const SET_ROLES = "SET_ROLES"

export const FETCH_START = "FETCH_START"
export const FETCH_STOP = "FETCH_STOP"
export const FILTER = "FILTER"

export const GET_LIST_CATEGORIES = "GET_LIST_CATEGORIES"
export const ADD_CATEGORIES = "ADD_CATEGORIES"
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES"
export const DELETE_CATEGORIES = "DELETE_CATEGORIES"
export const WAIT_CATEGORIES = "WAIT_ADD_CATEGORIES"
export const CATEGORIES_ERR = "CATEGORIES_ERR"

export const GET_LIST_RESTAURANTS = "GET_LIST_RESTAURANTS"
export const ADD_RESTAURANTS = "ADD_RESTAURANTS"
export const UPDATE_RESTAURANTS = "UPDATE_RESTAURANTS"
export const DELETE_RESTAURANTS = "DELETE_RESTAURANTS"
export const WAIT_RESTAURANTS = "WAIT_ADD_RESTAURANTS"
export const RESTAURANTS_ERR = "RESTAURANTS_ERR"

//restaurant user
export const GET_LIST_RESTAURANT_USERS = "GET_LIST_RESTAURANT_USERS"
export const ADD_RESTAURANT_USERS = "ADD_RESTAURANT_USERS"
export const UPDATE_RESTAURANT_USERS = "UPDATE_RESTAURANT_USERS"
export const DELETE_RESTAURANT_USERS = "DELETE_RESTAURANT_USERS"
export const WAIT_RESTAURANT_USERS = "WAIT_ADD_RESTAURANT_USERS"
export const RESTAURANT_USERS_ERR = "RESTAURANT_USERS_ERR"

//restaurant email
export const GET_LIST_RESTAURANT_EMAILS = "GET_LIST_RESTAURANT_EMAILS"
export const ADD_RESTAURANT_EMAILS = "ADD_RESTAURANT_EMAILS"
export const UPDATE_RESTAURANT_EMAILS = "UPDATE_RESTAURANT_EMAILS"
export const DELETE_RESTAURANT_EMAILS = "DELETE_RESTAURANT_EMAILS"
export const WAIT_RESTAURANT_EMAILS = "WAIT_ADD_RESTAURANT_EMAILS"
export const RESTAURANT_EMAILS_ERR = "RESTAURANT_EMAILS_ERR"

//foods
export const GET_LIST_FOODS = "GET_LIST_FOODS"
export const ADD_FOODS = "ADD_FOODS"
export const UPDATE_FOODS = "UPDATE_FOODS"
export const DELETE_FOODS = "DELETE_FOODS"
export const WAIT_FOODS = "WAIT_ADD_FOODS"
export const FOODS_ERR = "FOODS_ERR"

//food options
export const GET_LIST_FOOD_OPTIONS = "GET_LIST_FOOD_OPTIONS"
export const ADD_FOOD_OPTIONS = "ADD_FOOD_OPTIONS"
export const UPDATE_FOOD_OPTIONS = "UPDATE_FOOD_OPTIONS"
export const DELETE_FOOD_OPTIONS = "DELETE_FOOD_OPTIONS"
export const WAIT_FOOD_OPTIONS = "WAIT_ADD_FOOD_OPTIONS"
export const FOOD_OPTIONS_ERR = "FOOD_OPTIONS_ERR"

//orders
export const GET_LIST_ORDERS = "GET_LIST_ORDERS"
export const ADD_ORDERS = "ADD_ORDERS"
export const UPDATE_ORDERS = "UPDATE_ORDERS"
export const DELETE_ORDERS = "DELETE_ORDERS"
export const WAIT_ORDERS = "WAIT_ADD_ORDERS"
export const ORDERS_ERR = "ORDERS_ERR"

//payments
export const GET_LIST_PAYMENTS = "GET_LIST_PAYMENTS"
export const ADD_PAYMENTS = "ADD_PAYMENTS"
export const UPDATE_PAYMENTS = "UPDATE_PAYMENTS"
export const WAIT_PAYMENTS= "WAIT_ADD_PAYMENTS"
export const PAYMENTS_ERR = "PAYMENTS_ERR"

//actions type user
export const GET_LIST_USERS = "GET_LIST_USERS"
export const ADD_USERS = "ADD_USERS"
export const UPDATE_USERS = "UPDATE_USERS"
export const WAIT_USERS = "WAIT_ADD_USERS"
export const USERS_ERR = "USERS_ERR"


export const AUTH_SIGN_IN = "AUTH_SIGN_IN"
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT"
export const AUTH_LOGINING = "AUTH_LOGINING"
export const AUTH_LOGIN_ERR = "AUTH_LOGIN_ERR"
